---
title: "dipterancos"
author: "Rachel Behm"
date: "February 19, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Load packages
```{r}
library(tidyverse) 
library(RColorBrewer)
library(forcats)

```

2. load and wrangle data
```{r}
alldiptera<- read_csv("ncosdipwithhabitatedit.csv")


#make df way less obnoxious
dipncos <-alldiptera %>%
  select(
    order, family, scientificName, year, month, eventDate, verbatimEventDate, samplingProtocol, habitat, country, stateProvince, county, municipality, decimalLatitude, decimalLongitude, recordedBy) %>%
  mutate(
      monthname = case_when(
  month == 3 ~ "march",
  month == 4 ~ "april",
  month == 9 ~"september")
  ) %>%
  mutate(
    datenamemonth = (
      case_when(
        verbatimEventDate == "10.III.2016" ~"October",
        verbatimEventDate == "13-Sep-17" ~"September",
        verbatimEventDate == "Apr 14-15, 2016" ~ "April",
        verbatimEventDate == "Apr. 28-May 05, 2016" ~"April/May",
        verbatimEventDate == "April 19-20, 2016" ~"April",
        verbatimEventDate == "April 21-28, 2016" ~"April",
        verbatimEventDate == "April 26-27, 2016" ~"April",
        verbatimEventDate == "April 6-7, 2016" ~"April",
        verbatimEventDate == "April 7-14, 2016" ~"April",
        verbatimEventDate == "Jul 22-29, 2016" ~"July",
        verbatimEventDate == "July 14-15, 2016"~ "July",
        verbatimEventDate == "June 23-24, 2016" ~"June",
        verbatimEventDate == "Mar 31-Apr 1, 2016" ~"March/April",
        verbatimEventDate == "May 23-24, 2016" ~"May",
        verbatimEventDate == "Nov 16-23, 2016" ~"November"
 
        ))
  )
  


```

3. data exploration
```{r}
#get rid of giganctic NA column for things not yet ID'd
ncosdipbar <- dipncos %>% filter(family != "NA")

#fcy_infreq makes the bars go in decreasong order
familyabund<- ggplot(mutate
                     (ncosdipbar, family = fct_infreq(family))) + 
  geom_bar(
    aes(x = family, fill= family)) +
  labs(x="Family-level Identification", y="Number of specimens collected", title = "Diptera abundance before restoration") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()
        )
#theme stuff makes it so theres no x axis info

familyabund
########################################################################################

traptype <- familyabund + facet_wrap(~samplingProtocol) +labs(title = "Diptera abundance by sampling protocol")
traptype

########################################################################################

yeardip <- familyabund + facet_wrap(~verbatimEventDate) + labs(title = "Diptera abundance by date")
yeardip
########################################################################################

monthdip<- familyabund +facet_wrap(~monthname) + labs("Diptera by month")
monthdip
#######################################################################################
#these habitats are inputed terribly ill have to manually rename them in the csv


habdip <- familyabund + facet_wrap(~habitat) + labs(title = "Diptera abundance by habitat")
habdip
```

